---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=freescout
      - MARIADB_USER=freescout
    ports:
      - "3306:3306"
    networks:
      - freescout

  app:
    image: penguintech/freescout
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - mariadb
    networks:
      - freescout
    healthcheck:
      test: ["CMD", "ansible-playbook", "oldupstart.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  freescout:
