---
- name: Install freescout server
  hosts: localhost
  connection: local
  vars_files:
    - vars/prod.yml
  tasks:
    - name: Install Freescout Dependencies
      include_tasks:
        file: jobs/build/install_dependencies.yml
        apply:
          tags:
          - nginx
          - php
          - build
      tags:
      - nginx
      - php
      - build

    - name: Install Freescout
      include_tasks:
        file: jobs/build/install_freescout.yml
        apply:
          tags:
          - freescout
          - build
      tags:
        - freescout
        - build

    - name: Generate SSL certificate
      include_tasks:
        file: jobs/run/ssl_generate.yml
        apply:
          tags:
          - sslcertificate
          - run
      tags:
      - sslcertificate
      - run

    - name: Configure NGINX
      include_tasks:
        file: jobs/run/config_nginx.yml
        apply:
          tags:
          - nginx
          - run
      tags:
      - nginx
      - run

    - name: Configure freescout
      include_tasks:
        file: jobs/run/freescout_config.yml
        apply:
          tags:
          - config-freescout
          - run
      tags:
      - config_freescout
      - run

    - name: Run nginx
      include_tasks:
        file: jobs/run/nginx.yml
        apply:
          tags:
            - nginx
            - run
      tags:
        - nginx
        - run

    - name: Test database connectivity
      include_tasks:
        file: jobs/tests/database_test.yml
        apply:
          tags:
          - database
          - test
          - run
      tags:
      - database
      - test
      - run

    - name: Test Nginx
      include_tasks:
        file: jobs/tests/nginx_test.yml
        apply:
          tags:
          - nginx
          - test
          - run
      tags:
      - nginx
      - test
      - run

    - name: Test URL
      include_tasks:
        file: jobs/tests/freescout_test.yml
        apply:
          tags:
            - url
            - test
            - run
      tags:
        - url
        - test
        - run

    - name: Execute NGINX
      include_tasks:
        file: jobs/exec/nginx.yml
        apply:
          tags:
          - exec
      tags:
      - exec
