---
run:
  user: ptg-user

app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE') }}"
  link: "{{ lookup('env', 'APP_LINK') }}"

database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"

organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"

url: "{{ lookup('env', 'URL') }}"

file_limit: "{{ lookup('env', 'FILE_LIMIT') }}"

server_address: "{{ lookup('env', 'SERVER_ADDRESS') }}"

ssl_cert: "{{ lookup('env', 'SSL_CERT') }}"

protocol: "{{ lookup('env', 'PROTOCOL') }}"

module_links:
  - https://github.com/LJPc-solutions/freescout-calendar-module/archive/refs/heads/main.zip
  - https://github.com/freescout-helpdesk/freescout/files/6068564/Darkmode.zip

app_link: "{{ lookup('env', 'APP_LINK') }}"

admin:
  name: "{{ lookup('env', 'ADMIN_NAME') }}"
  lastname: "{{ lookup('env', 'ADMIN_LASTNAME') }}"
  email: "{{ lookup('env', 'ADMIN_EMAIL') }}"
  password: "{{ lookup('env', 'ADMIN_PASSWORD') }}"

ports:
  http: "{{ lookup('env', 'HTTP_PORT') }}"
  https: "{{ lookup('env', 'HTTPS_PORT') }}"

ports_test:
  - 8080
  - 8443
