---
- name: Configure nginx .conf
  template:
    src: /opt/manager/templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Configure nginx weberver
  template:
    src: /opt/manager/templates/freescout_http.j2
    dest: /etc/nginx/conf.d/freescout_http.conf
  when: protocol == "http"

- name: Configure nginx https webserver
  template:
    src: /opt/manager/templates/freescout_https.j2
    dest: /etc/nginx/conf.d/freescout_https.conf
    force: yes
  when: protocol == "https"




